import {Engine,ABI} from '../src/engine.js';
const out=document.querySelector('#log');let report=null;
function assert(condition,message){if(!condition)throw Error(message);out.textContent+=`PASS ${message}\n`;report.checks.push({name:message,passed:true});}
function fingerprint(a){let h=2166136261;const bytes=new Uint8Array(a.buffer,a.byteOffset,a.byteLength);for(const x of bytes){h^=x;h=Math.imul(h,16777619);}return h>>>0;}
document.querySelector('#run').onclick=async()=>{document.querySelector('#run').disabled=true;out.textContent='Starting real WebGPU…\n';report={date:new Date().toISOString(),checks:[],benchmark:false};let e;try{
 e=await new Engine(document.querySelector('canvas')).init({width:512,height:384,onProgress:s=>out.textContent=s+'\n',onError:err=>out.textContent+='DEVICE ERROR '+err.message+'\n'});report.adapter=e.info;out.textContent=JSON.stringify(e.info,null,2)+'\n';
 const [p,keys,nodes]=await Promise.all([e.runtime.read(e.buffers.P),e.runtime.read(e.buffers.Keys,Uint32Array),e.runtime.read(e.buffers.Nodes)]);const before=fingerprint(p);
 assert(Array.from(p).every(Number.isFinite),'generated primitive data is finite');let wood=0,leaves=0;for(let i=0;i<ABI.CAPACITY;i++){wood+=p[i*ABI.PS+3]===0;leaves+=p[i*ABI.PS+3]===1;}assert(wood===ABI.WOOD_COUNT&&leaves===ABI.LEAF_COUNT,'exact woody-segment and leaf counts');assert(nodes[11]===ABI.OBJECT_COUNT,'BVH root contains all objects');assert(keys.every((v,i)=>i===0||v>=keys[i-1]),'actual GPU bitonic result is sorted');
 e.input[5]=1;e.frame();e.input.fill(0);e.frame();await e.runtime.idle();const pixels=await e.screenshotPixels();let opaque=true,minimum=255,maximum=0;for(let i=0;i<pixels.length;i+=4){opaque&&=pixels[i+3]===255;minimum=Math.min(minimum,pixels[i]);maximum=Math.max(maximum,pixels[i]);}assert(opaque,'all output pixels have defined opaque alpha');assert(maximum-minimum>40,'rendered frame is nonconstant');
 const linear=await e.runtime.read(e.buffers.Linear);assert(linear.every(v=>Number.isFinite(v)&&v>=0),'HDR output is finite and nonnegative');
 e.input[5]=2;e.frame();e.input.fill(0);await e.runtime.idle();const after=await e.runtime.read(e.buffers.P);assert(fingerprint(after)===before,'camera approach does not replace, shrink or remove geometry');const c=await e.runtime.read(e.buffers.C);assert(c[3]<2,'close-up camera preset executed on GPU');
 assert(e.errors.length===0,'no reported WebGPU validation errors');report.inspection=await e.inspect();report.passed=true;out.textContent+='\nALL CHECKS PASSED on the reported adapter.\n';
 }catch(err){report.passed=false;report.error=err.stack||String(err);out.textContent+='\nFAIL '+report.error+'\n';console.error(err);}finally{document.querySelector('#run').disabled=false;document.querySelector('#save').disabled=false;if(e)await e.dispose();}};
document.querySelector('#save').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='arbor-webgpu-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
